// src/storage/condDefaults.ts
// Condições de trabalho predefinidas (modelo da folha de referência),
// traduzidas e adaptadas por língua. São apenas o ponto de partida —
// o utilizador edita tudo no Perfil.
import type { CondBox } from "./profile";

const PT: CondBox[] = [
  { titulo: "HORA EXTRA A", texto: "* São cobradas Horas Extra A (x1,5), a partir do início da 12ª hora de trabalho." },
  { titulo: "HORA EXTRA B", texto: "* São cobradas Horas Extra B (x2), a partir do início da 19ª hora de trabalho." },
  { titulo: "HORA RECUPERAÇÃO", texto: "* São cobradas Horas Extra de Recuperação (x3), se o intervalo entre o final de um dia de trabalho e o início do dia seguinte for inferior a 10 horas." },
  { titulo: "REFEIÇÃO", texto: "* Caso a pausa para refeição seja inferior a 01 hora, ou não ocorrer durante a rodagem, será incluída nas horas de trabalho, e poderá ser contabilizada como uma hora extraordinária. Em horários que terminem entre as 20h e as 22h é devida uma refeição servida ou paga, que será incluída nas horas de trabalho." },
  { titulo: "2ª REFEIÇÃO NO FINAL DO HORÁRIO DE TRABALHO", texto: "* Preparação: Em horários que terminem após as 20h (15€).\n* Dias de Rodagem: 21h (Horário de Inverno) ou 22h (Horário de Verão). Quando não é feita uma pausa para a 2ª refeição, deverá ser acrescentada 01:00 no final do dia de trabalho, que será incluída nas horas de trabalho. Só após o final dessa hora será iniciada a contagem das horas de recuperação." },
  { titulo: "HORÁRIO CONTÍNUO", texto: "* A pausa de refeição deve ser feita até à 7ª hora consecutiva de trabalho, podendo o dia de trabalho incluir o tempo de transporte em função da distância a percorrer até ao local de filmagem. Caso isso não aconteça, considera-se o horário de trabalho como horário contínuo.\nNestes casos as horas extraordinárias começam a ser contabilizadas a partir da 8ª hora, contabilizando desde logo a hora da refeição como hora extraordinária." },
  { titulo: "DESLOCAÇÕES", texto: "* A partir da Praça Marquês de Pombal (Lisboa) ou do hotel, caso seja esse o alojamento, os tempos de transporte serão calculados da seguinte forma:\n* Zona 0 – Lisboa Concelho — não se cobra tempo de transporte\n* Zona 1 – num percurso entre 10 Km a 25 Km — 30m por percurso\n* Zona 2 – num percurso entre 25 Km a 45 Km — 45m por percurso\n* Zona 3 – num percurso entre 45 Km a 80 Km — 60m (01H00) por percurso\n* Zona 4 – acima de 80 Km ou 1H de transporte — direito a alojamento.\n* Caso haja tempo de transporte, a pausa de refeição deve ser feita até à 7ª hora consecutiva de trabalho a contar a partir do local onde se inicia o transporte. Caso isso não aconteça, considera-se o horário de trabalho como horário contínuo." },
  { titulo: "UTILIZAÇÃO DE VIATURA PRÓPRIA", texto: "* Cabe à Produtora providenciar transporte para efetuar visitas técnicas enquadradas no âmbito profissional.\n* No caso de ser requisitada a utilização da viatura própria para Preparação, visita a locais de filmagem (Recce/Repérage), ou Filmagem, o pagamento de combustível, portagens, parqueamento, quilometragem, e aluguer deverá ser assegurado pela Produtora." },
  { titulo: "DIA DE VIAGEM", texto: "* O Dia de Viagem é pago como meio dia de salário diário, até 05 horas de viagem/trabalho.\nPara além das 05 horas, será cobrado um dia completo de salário." },
  { titulo: "TELEFONE", texto: "* No caso da utilização regular de telefone próprio para chamadas internacionais para fora da U.E. (União Europeia), poderá ser cobrado um valor diário indicado acima." },
  { titulo: "ALOJAMENTO", texto: "* O Alojamento é da responsabilidade da Produtora, em quartos individuais, com pagamento de despesas inerentes, ou de despesas de deslocação/Per Diems." },
  { titulo: "PER DIEMS", texto: "* Em viagens domésticas (dentro do país) – refeições diárias incluídas (pequeno-almoço, almoço ou jantar):\n• No caso de não serem fornecidas nenhuma das refeições, os per diems têm o valor de: 40€ por dia (24 horas);\n• No caso de serem servidas duas das três refeições diárias, os per diems têm o valor de: 20€ diários (24 horas).\n* Em viagens para fora do país de residência – refeições diárias incluídas (pequeno-almoço, almoço ou jantar):\n• No caso de não serem fornecidas nenhuma das refeições, o valor dos per diems é de: 50€ por dia (24 horas);\n• No caso de serem servidas duas das três refeições diárias, os per diems têm o valor de: 30€ por dia (24 horas).\n* Sendo uma retribuição, o montante pago a título de ajudas de custo deve constar do recibo de vencimento, discriminando a parte não sujeita a tributação e a parte sujeita (se a houver)." },
];

const EN: CondBox[] = [
  { titulo: "OVERTIME A", texto: "* Overtime A (x1.5) is charged from the start of the 12th hour of work." },
  { titulo: "OVERTIME B", texto: "* Overtime B (x2) is charged from the start of the 19th hour of work." },
  { titulo: "RECOVERY HOURS", texto: "* Recovery Overtime (x3) is charged if the interval between the end of a working day and the start of the next is less than 10 hours." },
  { titulo: "MEAL", texto: "* If the meal break is shorter than 1 hour, or does not take place during the shoot, it is included in working hours and may be counted as an overtime hour. On schedules ending between 8pm and 10pm a served or paid meal is due, included in working hours." },
  { titulo: "2ND MEAL AT THE END OF THE WORKING DAY", texto: "* Prep: on schedules ending after 8pm (€15).\n* Shooting days: 9pm (winter schedule) or 10pm (summer schedule). If no break is taken for the 2nd meal, 01:00 must be added at the end of the working day, included in working hours. Recovery hours only start counting after that hour ends." },
  { titulo: "CONTINUOUS SCHEDULE", texto: "* The meal break must be taken by the 7th consecutive hour of work; the working day may include transport time depending on the distance to the location. If this does not happen, the schedule counts as continuous.\nIn that case overtime starts counting from the 8th hour, with the meal hour immediately counted as overtime." },
  { titulo: "TRAVEL / DISTANCES", texto: "* From the meeting point defined by production (or the hotel, if that is the accommodation), transport time is calculated as follows:\n* Zone 0 – city area — no transport time charged\n* Zone 1 – 10 to 25 km — 30 min per trip\n* Zone 2 – 25 to 45 km — 45 min per trip\n* Zone 3 – 45 to 80 km — 60 min (1h) per trip\n* Zone 4 – above 80 km or 1h of transport — right to accommodation.\n* Where there is transport time, the meal break must be taken by the 7th consecutive hour counted from where transport starts; otherwise the schedule counts as continuous." },
  { titulo: "USE OF OWN VEHICLE", texto: "* The production company must provide transport for professional technical visits.\n* If the technician's own vehicle is requested for prep, location scouting (recce) or shooting, fuel, tolls, parking, mileage and rental must be covered by the production company." },
  { titulo: "TRAVEL DAY", texto: "* A travel day is paid as half a daily rate, up to 5 hours of travel/work.\nBeyond 5 hours, a full daily rate is charged." },
  { titulo: "PHONE", texto: "* Where the technician's own phone is regularly used for international calls outside the EU, the daily amount indicated above may be charged." },
  { titulo: "ACCOMMODATION", texto: "* Accommodation is the production company's responsibility, in single rooms, with inherent expenses paid, or travel expenses/per diems." },
  { titulo: "PER DIEMS", texto: "* Domestic travel (within the country) – daily meals included (breakfast, lunch or dinner):\n• If none of the meals are provided, per diems amount to: €40 per day (24 hours);\n• If two of the three daily meals are served, per diems amount to: €20 per day (24 hours).\n* Travel outside the country of residence – daily meals included:\n• If none of the meals are provided, per diems amount to: €50 per day (24 hours);\n• If two of the three daily meals are served, per diems amount to: €30 per day (24 hours).\n* As remuneration, per diem amounts must appear on the payslip, separating the non-taxable and taxable parts (if any)." },
];

const ES: CondBox[] = [
  { titulo: "HORA EXTRA A", texto: "* Se cobran Horas Extra A (x1,5) a partir del inicio de la 12ª hora de trabajo." },
  { titulo: "HORA EXTRA B", texto: "* Se cobran Horas Extra B (x2) a partir del inicio de la 19ª hora de trabajo." },
  { titulo: "HORA DE RECUPERACIÓN", texto: "* Se cobran Horas Extra de Recuperación (x3) si el intervalo entre el final de un día de trabajo y el inicio del siguiente es inferior a 10 horas." },
  { titulo: "COMIDA", texto: "* Si la pausa para comer es inferior a 1 hora, o no se produce durante el rodaje, se incluirá en las horas de trabajo y podrá contabilizarse como hora extraordinaria. En jornadas que terminen entre las 20h y las 22h se debe una comida servida o pagada, incluida en las horas de trabajo." },
  { titulo: "2ª COMIDA AL FINAL DE LA JORNADA", texto: "* Preparación: en jornadas que terminen después de las 20h (15€).\n* Días de rodaje: 21h (horario de invierno) o 22h (horario de verano). Si no se hace pausa para la 2ª comida, se añadirá 01:00 al final de la jornada, incluida en las horas de trabajo. Las horas de recuperación solo empiezan a contar después de esa hora." },
  { titulo: "JORNADA CONTINUA", texto: "* La pausa para comer debe hacerse antes de la 7ª hora consecutiva de trabajo; la jornada puede incluir el tiempo de transporte según la distancia a la localización. Si no ocurre, la jornada se considera continua.\nEn ese caso, las horas extra empiezan a contar desde la 8ª hora, contabilizando la hora de la comida como extraordinaria." },
  { titulo: "DESPLAZAMIENTOS", texto: "* Desde el punto de encuentro definido por producción (o el hotel, si es el alojamiento), el tiempo de transporte se calcula así:\n* Zona 0 – área urbana — no se cobra tiempo de transporte\n* Zona 1 – de 10 a 25 km — 30 min por trayecto\n* Zona 2 – de 25 a 45 km — 45 min por trayecto\n* Zona 3 – de 45 a 80 km — 60 min (1h) por trayecto\n* Zona 4 – más de 80 km o 1h de transporte — derecho a alojamiento.\n* Si hay tiempo de transporte, la pausa para comer debe hacerse antes de la 7ª hora consecutiva contada desde donde empieza el transporte; si no, la jornada se considera continua." },
  { titulo: "USO DE VEHÍCULO PROPIO", texto: "* Corresponde a la productora facilitar transporte para las visitas técnicas profesionales.\n* Si se solicita el vehículo propio para preparación, localizaciones (recce) o rodaje, el combustible, peajes, aparcamiento, kilometraje y alquiler correrán a cargo de la productora." },
  { titulo: "DÍA DE VIAJE", texto: "* El día de viaje se paga como medio día de salario, hasta 5 horas de viaje/trabajo.\nMás allá de 5 horas se cobra un día completo de salario." },
  { titulo: "TELÉFONO", texto: "* Si se usa habitualmente el teléfono propio para llamadas internacionales fuera de la UE, podrá cobrarse el importe diario indicado arriba." },
  { titulo: "ALOJAMIENTO", texto: "* El alojamiento es responsabilidad de la productora, en habitaciones individuales, con gastos inherentes pagados, o gastos de desplazamiento/dietas." },
  { titulo: "DIETAS (PER DIEMS)", texto: "* Viajes nacionales – comidas diarias incluidas (desayuno, comida o cena):\n• Si no se proporciona ninguna comida, las dietas son de: 40€ al día (24 horas);\n• Si se sirven dos de las tres comidas diarias, las dietas son de: 20€ al día (24 horas).\n* Viajes fuera del país de residencia:\n• Si no se proporciona ninguna comida: 50€ al día (24 horas);\n• Si se sirven dos de las tres comidas: 30€ al día (24 horas).\n* Al ser retribución, el importe de las dietas debe constar en la nómina, separando la parte exenta y la sujeta (si la hay)." },
];

const FR: CondBox[] = [
  { titulo: "HEURE SUP A", texto: "* Les Heures Supplémentaires A (x1,5) sont facturées à partir du début de la 12ᵉ heure de travail." },
  { titulo: "HEURE SUP B", texto: "* Les Heures Supplémentaires B (x2) sont facturées à partir du début de la 19ᵉ heure de travail." },
  { titulo: "HEURE DE RÉCUPÉRATION", texto: "* Les Heures de Récupération (x3) sont facturées si l'intervalle entre la fin d'une journée de travail et le début de la suivante est inférieur à 10 heures." },
  { titulo: "REPAS", texto: "* Si la pause repas est inférieure à 1 heure, ou n'a pas lieu pendant le tournage, elle est incluse dans les heures de travail et peut être comptée comme heure supplémentaire. Pour les horaires se terminant entre 20h et 22h, un repas servi ou payé est dû, inclus dans les heures de travail." },
  { titulo: "2ᵉ REPAS EN FIN DE JOURNÉE", texto: "* Préparation : horaires se terminant après 20h (15€).\n* Jours de tournage : 21h (horaire d'hiver) ou 22h (horaire d'été). Sans pause pour le 2ᵉ repas, 01:00 doit être ajoutée en fin de journée, incluse dans les heures de travail. Les heures de récupération ne commencent qu'après cette heure." },
  { titulo: "JOURNÉE CONTINUE", texto: "* La pause repas doit être prise avant la 7ᵉ heure consécutive de travail ; la journée peut inclure le temps de transport selon la distance jusqu'au lieu de tournage. À défaut, l'horaire est considéré comme continu.\nDans ce cas, les heures supplémentaires comptent dès la 8ᵉ heure, l'heure du repas étant immédiatement comptée en heure sup." },
  { titulo: "DÉPLACEMENTS", texto: "* Depuis le point de rendez-vous défini par la production (ou l'hôtel, si c'est l'hébergement), le temps de transport est calculé ainsi :\n* Zone 0 – zone urbaine — pas de temps de transport facturé\n* Zone 1 – de 10 à 25 km — 30 min par trajet\n* Zone 2 – de 25 à 45 km — 45 min par trajet\n* Zone 3 – de 45 à 80 km — 60 min (1h) par trajet\n* Zone 4 – au-delà de 80 km ou 1h de transport — droit à l'hébergement.\n* S'il y a du temps de transport, la pause repas doit être prise avant la 7ᵉ heure consécutive comptée depuis le départ du transport ; sinon l'horaire est considéré comme continu." },
  { titulo: "UTILISATION DU VÉHICULE PERSONNEL", texto: "* Il appartient à la production de fournir le transport pour les visites techniques professionnelles.\n* Si le véhicule personnel est demandé pour la préparation, les repérages ou le tournage, le carburant, les péages, le parking, le kilométrage et la location sont à la charge de la production." },
  { titulo: "JOUR DE VOYAGE", texto: "* Le jour de voyage est payé une demi-journée de salaire, jusqu'à 5 heures de voyage/travail.\nAu-delà de 5 heures, une journée complète est facturée." },
  { titulo: "TÉLÉPHONE", texto: "* En cas d'utilisation régulière du téléphone personnel pour des appels internationaux hors UE, le montant journalier indiqué ci-dessus peut être facturé." },
  { titulo: "HÉBERGEMENT", texto: "* L'hébergement est à la charge de la production, en chambres individuelles, avec les frais inhérents payés, ou des frais de déplacement/per diems." },
  { titulo: "PER DIEMS", texto: "* Voyages nationaux – repas quotidiens inclus (petit-déjeuner, déjeuner ou dîner) :\n• Si aucun repas n'est fourni, les per diems s'élèvent à : 40€ par jour (24 heures) ;\n• Si deux des trois repas quotidiens sont servis : 20€ par jour (24 heures).\n* Voyages hors du pays de résidence :\n• Si aucun repas n'est fourni : 50€ par jour (24 heures) ;\n• Si deux des trois repas sont servis : 30€ par jour (24 heures).\n* S'agissant d'une rémunération, les per diems doivent figurer sur la fiche de paie, en distinguant la part exonérée et la part imposable (le cas échéant)." },
];

const DE: CondBox[] = [
  { titulo: "ÜBERSTUNDEN A", texto: "* Überstunden A (x1,5) werden ab Beginn der 12. Arbeitsstunde berechnet." },
  { titulo: "ÜBERSTUNDEN B", texto: "* Überstunden B (x2) werden ab Beginn der 19. Arbeitsstunde berechnet." },
  { titulo: "ERHOLUNGSSTUNDEN", texto: "* Erholungs-Überstunden (x3) werden berechnet, wenn der Abstand zwischen dem Ende eines Arbeitstags und dem Beginn des nächsten weniger als 10 Stunden beträgt." },
  { titulo: "VERPFLEGUNG", texto: "* Ist die Essenspause kürzer als 1 Stunde oder findet sie während des Drehs nicht statt, wird sie in die Arbeitszeit einbezogen und kann als Überstunde gezählt werden. Bei Arbeitszeiten mit Ende zwischen 20 und 22 Uhr ist eine servierte oder bezahlte Mahlzeit geschuldet, die in die Arbeitszeit einfließt." },
  { titulo: "2. MAHLZEIT AM ENDE DES ARBEITSTAGS", texto: "* Vorbereitung: bei Arbeitsende nach 20 Uhr (15 €).\n* Drehtage: 21 Uhr (Winter) bzw. 22 Uhr (Sommer). Wird keine Pause für die 2. Mahlzeit gemacht, ist am Ende des Arbeitstags 01:00 hinzuzufügen, die in die Arbeitszeit einfließt. Die Erholungsstunden beginnen erst nach Ablauf dieser Stunde." },
  { titulo: "DURCHGEHENDE ARBEITSZEIT", texto: "* Die Essenspause muss bis zur 7. aufeinanderfolgenden Arbeitsstunde erfolgen; der Arbeitstag kann die Transportzeit je nach Entfernung zum Drehort einschließen. Andernfalls gilt die Arbeitszeit als durchgehend.\nIn diesem Fall zählen Überstunden ab der 8. Stunde, wobei die Essensstunde sofort als Überstunde zählt." },
  { titulo: "FAHRTEN / ENTFERNUNGEN", texto: "* Ab dem von der Produktion definierten Treffpunkt (oder dem Hotel, falls dort untergebracht) wird die Transportzeit wie folgt berechnet:\n* Zone 0 – Stadtgebiet — keine Transportzeit\n* Zone 1 – 10 bis 25 km — 30 Min. pro Strecke\n* Zone 2 – 25 bis 45 km — 45 Min. pro Strecke\n* Zone 3 – 45 bis 80 km — 60 Min. (1h) pro Strecke\n* Zone 4 – über 80 km oder 1h Transport — Anspruch auf Unterkunft.\n* Bei Transportzeit muss die Essenspause bis zur 7. aufeinanderfolgenden Stunde ab Transportbeginn erfolgen; andernfalls gilt die Arbeitszeit als durchgehend." },
  { titulo: "NUTZUNG DES EIGENEN FAHRZEUGS", texto: "* Die Produktion stellt den Transport für berufliche technische Besichtigungen.\n* Wird das eigene Fahrzeug für Vorbereitung, Motivbesichtigung (Recce) oder Dreh angefordert, übernimmt die Produktion Kraftstoff, Maut, Parken, Kilometergeld und Miete." },
  { titulo: "REISETAG", texto: "* Ein Reisetag wird mit einer halben Tagesgage vergütet, bis zu 5 Stunden Reise/Arbeit.\nÜber 5 Stunden hinaus wird eine volle Tagesgage berechnet." },
  { titulo: "TELEFON", texto: "* Bei regelmäßiger Nutzung des eigenen Telefons für internationale Anrufe außerhalb der EU kann der oben angegebene Tagesbetrag berechnet werden." },
  { titulo: "UNTERKUNFT", texto: "* Die Unterkunft liegt in der Verantwortung der Produktion, in Einzelzimmern, mit Übernahme der anfallenden Kosten oder Reisekosten/Per Diems." },
  { titulo: "PER DIEMS", texto: "* Inlandsreisen – tägliche Mahlzeiten inbegriffen (Frühstück, Mittag- oder Abendessen):\n• Wird keine Mahlzeit gestellt, betragen die Per Diems: 40 € pro Tag (24 Stunden);\n• Werden zwei der drei täglichen Mahlzeiten serviert: 20 € pro Tag (24 Stunden).\n* Reisen außerhalb des Wohnsitzlandes:\n• Wird keine Mahlzeit gestellt: 50 € pro Tag (24 Stunden);\n• Werden zwei der drei Mahlzeiten serviert: 30 € pro Tag (24 Stunden).\n* Als Vergütung müssen Per Diems auf der Abrechnung erscheinen, getrennt nach steuerfreiem und steuerpflichtigem Anteil (falls vorhanden)." },
];

const IT: CondBox[] = [
  { titulo: "STRAORDINARIO A", texto: "* Lo Straordinario A (x1,5) viene addebitato dall'inizio della 12ª ora di lavoro." },
  { titulo: "STRAORDINARIO B", texto: "* Lo Straordinario B (x2) viene addebitato dall'inizio della 19ª ora di lavoro." },
  { titulo: "ORE DI RECUPERO", texto: "* Le Ore di Recupero (x3) vengono addebitate se l'intervallo tra la fine di una giornata di lavoro e l'inizio della successiva è inferiore a 10 ore." },
  { titulo: "PASTO", texto: "* Se la pausa pasto è inferiore a 1 ora, o non avviene durante le riprese, viene inclusa nelle ore di lavoro e può essere conteggiata come ora straordinaria. Per orari che terminano tra le 20 e le 22 è dovuto un pasto servito o pagato, incluso nelle ore di lavoro." },
  { titulo: "2º PASTO A FINE GIORNATA", texto: "* Preparazione: per orari che terminano dopo le 20 (15€).\n* Giorni di riprese: ore 21 (orario invernale) o 22 (orario estivo). Se non viene fatta la pausa per il 2º pasto, va aggiunta 01:00 alla fine della giornata, inclusa nelle ore di lavoro. Le ore di recupero iniziano a contare solo dopo quella ora." },
  { titulo: "ORARIO CONTINUATO", texto: "* La pausa pasto deve avvenire entro la 7ª ora consecutiva di lavoro; la giornata può includere il tempo di trasporto in base alla distanza dalla location. In caso contrario l'orario si considera continuato.\nIn tal caso gli straordinari contano dall'8ª ora, conteggiando subito l'ora del pasto come straordinario." },
  { titulo: "TRASFERIMENTI", texto: "* Dal punto d'incontro definito dalla produzione (o dall'hotel, se è l'alloggio), il tempo di trasporto si calcola così:\n* Zona 0 – area urbana — nessun tempo di trasporto\n* Zona 1 – da 10 a 25 km — 30 min a tratta\n* Zona 2 – da 25 a 45 km — 45 min a tratta\n* Zona 3 – da 45 a 80 km — 60 min (1h) a tratta\n* Zona 4 – oltre 80 km o 1h di trasporto — diritto all'alloggio.\n* Se c'è tempo di trasporto, la pausa pasto deve avvenire entro la 7ª ora consecutiva contata da dove inizia il trasporto; altrimenti l'orario si considera continuato." },
  { titulo: "USO DEL VEICOLO PROPRIO", texto: "* Spetta alla produzione fornire il trasporto per i sopralluoghi tecnici professionali.\n* Se viene richiesto il veicolo proprio per preparazione, sopralluoghi (recce) o riprese, carburante, pedaggi, parcheggio, chilometraggio e noleggio sono a carico della produzione." },
  { titulo: "GIORNO DI VIAGGIO", texto: "* Il giorno di viaggio è pagato come mezza giornata di salario, fino a 5 ore di viaggio/lavoro.\nOltre le 5 ore viene addebitata una giornata intera." },
  { titulo: "TELEFONO", texto: "* In caso di uso regolare del telefono personale per chiamate internazionali fuori dall'UE, può essere addebitato l'importo giornaliero indicato sopra." },
  { titulo: "ALLOGGIO", texto: "* L'alloggio è a carico della produzione, in camere singole, con spese inerenti pagate, o spese di trasferta/per diem." },
  { titulo: "PER DIEM", texto: "* Trasferte nazionali – pasti giornalieri inclusi (colazione, pranzo o cena):\n• Se non viene fornito nessun pasto, i per diem ammontano a: 40€ al giorno (24 ore);\n• Se vengono serviti due dei tre pasti giornalieri: 20€ al giorno (24 ore).\n* Trasferte fuori dal paese di residenza:\n• Se non viene fornito nessun pasto: 50€ al giorno (24 ore);\n• Se vengono serviti due dei tre pasti: 30€ al giorno (24 ore).\n* Essendo retribuzione, i per diem devono comparire in busta paga, distinguendo la parte esente e quella imponibile (se presente)." },
];

const NL: CondBox[] = [
  { titulo: "OVERUREN A", texto: "* Overuren A (x1,5) worden gerekend vanaf het begin van het 12e werkuur." },
  { titulo: "OVERUREN B", texto: "* Overuren B (x2) worden gerekend vanaf het begin van het 19e werkuur." },
  { titulo: "HERSTELUREN", texto: "* Herstel-overuren (x3) worden gerekend als de tijd tussen het einde van een werkdag en het begin van de volgende minder dan 10 uur bedraagt." },
  { titulo: "MAALTIJD", texto: "* Als de maaltijdpauze korter is dan 1 uur, of niet plaatsvindt tijdens de opnames, wordt deze meegeteld in de werkuren en kan deze als overuur worden gerekend. Bij werkdagen die tussen 20u en 22u eindigen is een geserveerde of betaalde maaltijd verschuldigd, meegeteld in de werkuren." },
  { titulo: "2E MAALTIJD AAN HET EINDE VAN DE WERKDAG", texto: "* Voorbereiding: bij einde na 20u (€15).\n* Draaidagen: 21u (winterschema) of 22u (zomerschema). Als er geen pauze voor de 2e maaltijd wordt genomen, moet 01:00 aan het einde van de werkdag worden toegevoegd, meegeteld in de werkuren. Hersteluren beginnen pas na afloop van dat uur te tellen." },
  { titulo: "DOORLOPEND ROOSTER", texto: "* De maaltijdpauze moet uiterlijk in het 7e opeenvolgende werkuur worden genomen; de werkdag kan reistijd omvatten afhankelijk van de afstand tot de locatie. Gebeurt dit niet, dan geldt het rooster als doorlopend.\nIn dat geval tellen overuren vanaf het 8e uur, waarbij het maaltijduur direct als overuur telt." },
  { titulo: "REIZEN / AFSTANDEN", texto: "* Vanaf het door de productie bepaalde verzamelpunt (of het hotel, indien dat de accommodatie is) wordt de reistijd als volgt berekend:\n* Zone 0 – stadsgebied — geen reistijd gerekend\n* Zone 1 – 10 tot 25 km — 30 min per rit\n* Zone 2 – 25 tot 45 km — 45 min per rit\n* Zone 3 – 45 tot 80 km — 60 min (1u) per rit\n* Zone 4 – boven 80 km of 1u reistijd — recht op accommodatie.\n* Bij reistijd moet de maaltijdpauze uiterlijk in het 7e opeenvolgende uur vanaf het vertrekpunt worden genomen; anders geldt het rooster als doorlopend." },
  { titulo: "GEBRUIK EIGEN VOERTUIG", texto: "* De productie zorgt voor vervoer voor professionele technische bezoeken.\n* Als het eigen voertuig wordt gevraagd voor voorbereiding, locatiebezoek (recce) of opnames, komen brandstof, tol, parkeren, kilometervergoeding en huur voor rekening van de productie." },
  { titulo: "REISDAG", texto: "* Een reisdag wordt betaald als een halve daggage, tot 5 uur reizen/werken.\nBoven 5 uur wordt een volledige daggage gerekend." },
  { titulo: "TELEFOON", texto: "* Bij regelmatig gebruik van de eigen telefoon voor internationale gesprekken buiten de EU kan het hierboven vermelde dagbedrag worden gerekend." },
  { titulo: "ACCOMMODATIE", texto: "* Accommodatie is de verantwoordelijkheid van de productie, in eenpersoonskamers, met betaling van bijbehorende kosten, of reiskosten/per diems." },
  { titulo: "PER DIEMS", texto: "* Binnenlandse reizen – dagelijkse maaltijden inbegrepen (ontbijt, lunch of diner):\n• Als geen van de maaltijden wordt verstrekt, bedragen de per diems: €40 per dag (24 uur);\n• Als twee van de drie dagelijkse maaltijden worden geserveerd: €20 per dag (24 uur).\n* Reizen buiten het woonland:\n• Als geen van de maaltijden wordt verstrekt: €50 per dag (24 uur);\n• Als twee van de drie maaltijden worden geserveerd: €30 per dag (24 uur).\n* Als vergoeding moeten per diems op de loonstrook staan, met onderscheid tussen het belastingvrije en het belastbare deel (indien van toepassing)." },
];

const PL: CondBox[] = [
  { titulo: "NADGODZINY A", texto: "* Nadgodziny A (x1,5) naliczane są od początku 12. godziny pracy." },
  { titulo: "NADGODZINY B", texto: "* Nadgodziny B (x2) naliczane są od początku 19. godziny pracy." },
  { titulo: "GODZINY ODPOCZYNKU", texto: "* Nadgodziny za odpoczynek (x3) naliczane są, jeśli przerwa między końcem dnia pracy a początkiem następnego jest krótsza niż 10 godzin." },
  { titulo: "POSIŁEK", texto: "* Jeśli przerwa na posiłek jest krótsza niż 1 godzina lub nie odbywa się podczas zdjęć, wlicza się ją do godzin pracy i może być liczona jako nadgodzina. Przy pracy kończącej się między 20:00 a 22:00 należy się posiłek podany lub opłacony, wliczony w godziny pracy." },
  { titulo: "2. POSIŁEK NA KONIEC DNIA PRACY", texto: "* Przygotowanie: przy zakończeniu po 20:00 (15€).\n* Dni zdjęciowe: 21:00 (okres zimowy) lub 22:00 (okres letni). Jeśli nie ma przerwy na 2. posiłek, na koniec dnia pracy należy doliczyć 01:00, wliczone w godziny pracy. Godziny odpoczynku liczą się dopiero po upływie tej godziny." },
  { titulo: "PRACA CIĄGŁA", texto: "* Przerwa na posiłek musi nastąpić najpóźniej w 7. kolejnej godzinie pracy; dzień pracy może obejmować czas transportu zależnie od odległości do lokacji. W przeciwnym razie czas pracy uznaje się za ciągły.\nWówczas nadgodziny liczą się od 8. godziny, a godzina posiłku od razu liczy się jako nadgodzina." },
  { titulo: "DOJAZDY / ODLEGŁOŚCI", texto: "* Od punktu zbiórki wyznaczonego przez produkcję (lub hotelu, jeśli tam jest zakwaterowanie) czas transportu liczony jest następująco:\n* Strefa 0 – obszar miejski — bez naliczania czasu transportu\n* Strefa 1 – 10 do 25 km — 30 min za przejazd\n* Strefa 2 – 25 do 45 km — 45 min za przejazd\n* Strefa 3 – 45 do 80 km — 60 min (1h) za przejazd\n* Strefa 4 – powyżej 80 km lub 1h transportu — prawo do zakwaterowania.\n* Przy czasie transportu przerwa na posiłek musi nastąpić najpóźniej w 7. kolejnej godzinie liczonej od miejsca rozpoczęcia transportu; inaczej czas pracy uznaje się za ciągły." },
  { titulo: "UŻYCIE WŁASNEGO POJAZDU", texto: "* Produkcja zapewnia transport na zawodowe wizyty techniczne.\n* Jeśli wymagane jest użycie własnego pojazdu do przygotowań, dokumentacji (recce) lub zdjęć, paliwo, opłaty drogowe, parking, kilometrówkę i wynajem pokrywa produkcja." },
  { titulo: "DZIEŃ PODRÓŻY", texto: "* Dzień podróży płatny jest jak pół stawki dziennej, do 5 godzin podróży/pracy.\nPowyżej 5 godzin naliczana jest pełna stawka dzienna." },
  { titulo: "TELEFON", texto: "* Przy regularnym używaniu własnego telefonu do połączeń międzynarodowych poza UE może być naliczana dzienna kwota wskazana powyżej." },
  { titulo: "ZAKWATEROWANIE", texto: "* Zakwaterowanie leży po stronie produkcji, w pokojach jednoosobowych, z pokryciem kosztów, lub kosztów podróży/diet." },
  { titulo: "DIETY (PER DIEM)", texto: "* Podróże krajowe – posiłki dzienne wliczone (śniadanie, obiad lub kolacja):\n• Jeśli żaden posiłek nie jest zapewniony, dieta wynosi: 40€ dziennie (24 godziny);\n• Jeśli podawane są dwa z trzech posiłków dziennie: 20€ dziennie (24 godziny).\n* Podróże poza kraj zamieszkania:\n• Jeśli żaden posiłek nie jest zapewniony: 50€ dziennie (24 godziny);\n• Jeśli podawane są dwa z trzech posiłków: 30€ dziennie (24 godziny).\n* Jako wynagrodzenie, diety muszą widnieć na pasku płacowym z podziałem na część zwolnioną i opodatkowaną (jeśli występuje)." },
];

export function condBoxesFor(locale: string): CondBox[] {
  const l = (locale || "pt").toLowerCase();
  if (l.startsWith("pt")) return PT;
  if (l.startsWith("es")) return ES;
  if (l.startsWith("fr")) return FR;
  if (l.startsWith("de")) return DE;
  if (l.startsWith("it")) return IT;
  if (l.startsWith("nl")) return NL;
  if (l.startsWith("pl")) return PL;
  return EN;
}
