// src/storage/condDefaultsCinema.ts
// Condições de trabalho predefinidas da folha de CINEMA (semanal) — o modelo
// da folha de referência do setor: horário de 11h (10h + 1h de refeição),
// recuperação entre dias e entre semanas (60h/36h), folgas e feriados a
// dobrar, refeições e deslocações. Ponto de partida; edita-se tudo no Perfil.
import type { CondBox } from "./profile";

const PT: CondBox[] = [
  { titulo: "HORA EXTRA A", texto: "* São cobradas Horas Extra A quando cumprido o Horário de Trabalho em vigor pelo Departamento (11 horas: 10h de trabalho + 1h de refeição).\n* Em horário contínuo, são cobradas a partir da 8ª hora de trabalho." },
  { titulo: "HORA EXTRA B", texto: "* São cobradas Horas Extra B conforme estipulado pelo Departamento." },
  { titulo: "HORA RECUPERAÇÃO", texto: "* Hora cobrada quando o intervalo entre dois dias consecutivos de trabalho é inferior a 10 horas, conforme estipulado pelo Departamento.\n* Hora cobrada quando o intervalo entre o último dia da semana e o início da semana seguinte é inferior a 60 horas (semana de 5 dias) ou 36 horas (semana de 6 dias). A meia hora é arredondada à hora seguinte." },
  { titulo: "DIA DE FOLGA E FERIADOS", texto: "* Se o Técnico for requisitado num Dia de Folga, mediante acordo de todas as partes, esse dia tem como referência o valor de um Dia Normal agravado a 100% (a dobrar), com as Horas Extra e de Recuperação também a dobrar.\n* Um Feriado Nacional Obrigatório que ocorra durante a semana de trabalho é cobrado como um dia normal a dobrar.\n* Se for acrescentado um sexto dia à semana de 5 dias, o descanso entre semanas passa a 36 horas." },
  { titulo: "REFEIÇÃO", texto: "* Caso a pausa para refeição seja inferior a 01 hora, ou não ocorrer durante a rodagem, será incluída nas horas de trabalho, e poderá ser contabilizada como uma hora extraordinária.\n* A partir das 20h00, ou após um intervalo máximo de 7 horas desde o fim da refeição anterior, é devida uma Segunda Refeição, com pausa não inferior a 30 minutos. Se a pausa não ocorrer, conta como hora extraordinária e a refeição é paga contra fatura (valor não inferior a 15€).\n* Caso o local ou catering não preencha os requisitos mínimos de higiene e qualidade, a refeição é paga contra fatura (valor não inferior a 15€)." },
  { titulo: "HORÁRIO CONTÍNUO", texto: "* A pausa de refeição deve ser feita até à 7ª hora consecutiva de trabalho no Set/Décor, a contar da Hora de Convocação (Crew Call). Caso isso não aconteça, considera-se o horário de trabalho como horário contínuo.\n* Nestes casos as horas extraordinárias começam a ser contabilizadas a partir da 8ª hora, contabilizando desde logo a hora da refeição como hora extraordinária." },
  { titulo: "DESLOCAÇÕES", texto: "* A partir da Praça Marquês de Pombal (Lisboa), da casa de aluguer de material ou do hotel, caso seja esse o alojamento, os tempos de transporte serão calculados da seguinte forma para veículos ligeiros:\n* Zona 0 – Lisboa Cidade — não se cobra tempo de transporte, desde que o Técnico não tenha de ir à casa de aluguer de material, garagem, etc.\n* Zona 1 – num percurso de 25 Km — 30m por percurso\n* Zona 2 – num percurso entre 25 Km a 50 Km — 45m por percurso\n* Zona 3 – num percurso entre 50 Km a 100 Km — 60m (01H00) por percurso\n* Zona 4 – acima de 100 Km ou 1H de transporte — direito a alojamento.\n* Caso não haja alojamento, a pausa de refeição deve ser feita até à 7ª hora consecutiva de trabalho a contar do local onde se inicia o transporte; caso contrário, considera-se horário contínuo.\n* Exceção: para os Técnicos que tenham de se deslocar a um local (casa de material, garagem ou outro) para conduzir um carro de material, o Dia de Trabalho inicia-se nesse local." },
];

const EN: CondBox[] = [
  { titulo: "OVERTIME A", texto: "* Overtime A is charged once the Department's working day is complete (11 hours: 10h of work + 1h meal).\n* On a continuous schedule it is charged from the 8th hour of work." },
  { titulo: "OVERTIME B", texto: "* Overtime B is charged as stipulated by the Department." },
  { titulo: "RECOVERY HOURS", texto: "* Charged when the break between two consecutive working days is under 10 hours, as stipulated by the Department.\n* Charged when the break between the last day of the week and the start of the next is under 60 hours (5-day week) or 36 hours (6-day week). Half an hour rounds up to the next hour." },
  { titulo: "DAYS OFF AND HOLIDAYS", texto: "* If the crew member is called in on a day off, by agreement of all parties, that day is paid at the normal day rate plus 100% (double), with overtime and recovery hours also doubled.\n* A mandatory public holiday falling within the working week is charged as a normal day, doubled.\n* If a sixth day is added to a 5-day week, the rest between weeks becomes 36 hours." },
  { titulo: "MEALS", texto: "* If the meal break is shorter than 1 hour, or does not happen during the shoot, it counts as working time and may be charged as overtime.\n* From 8 pm, or at most 7 hours after the end of the previous meal, a second meal is due, with a break of at least 30 minutes. If the break does not happen, it counts as overtime and the meal is paid against invoice (no less than €15).\n* If the venue or catering does not meet minimum hygiene and quality standards, the meal is paid against invoice (no less than €15)." },
  { titulo: "CONTINUOUS SCHEDULE", texto: "* The meal break must happen by the 7th consecutive hour of work on set, counted from crew call. Otherwise the day is treated as a continuous schedule.\n* In that case overtime starts from the 8th hour, with the meal hour itself already counted as overtime." },
  { titulo: "TRAVEL", texto: "* From Marquês de Pombal square (Lisbon), the equipment rental house or the hotel if that is the accommodation, travel time for light vehicles is calculated as follows:\n* Zone 0 – Lisbon city — no travel time charged, unless the crew member has to go to the rental house, garage, etc.\n* Zone 1 – up to 25 km — 30 min per leg\n* Zone 2 – 25 to 50 km — 45 min per leg\n* Zone 3 – 50 to 100 km — 60 min (1 h) per leg\n* Zone 4 – over 100 km or 1 h of travel — entitled to accommodation.\n* Without accommodation, the meal break must happen by the 7th consecutive hour counted from where travel starts; otherwise the day is a continuous schedule.\n* Exception: crew who must go to a location (rental house, garage or other) to drive an equipment vehicle start their working day there." },
];

const ES: CondBox[] = [
  { titulo: "HORA EXTRA A", texto: "* Se cobran Horas Extra A una vez cumplido el Horario de Trabajo vigente del Departamento (11 horas: 10h de trabajo + 1h de comida).\n* En horario continuo se cobran a partir de la 8ª hora de trabajo." },
  { titulo: "HORA EXTRA B", texto: "* Se cobran Horas Extra B según lo estipulado por el Departamento." },
  { titulo: "HORA DE RECUPERACIÓN", texto: "* Se cobra cuando el intervalo entre dos días consecutivos de trabajo es inferior a 10 horas, según lo estipulado por el Departamento.\n* Se cobra cuando el intervalo entre el último día de la semana y el inicio de la siguiente es inferior a 60 horas (semana de 5 días) o 36 horas (semana de 6 días). La media hora se redondea a la hora siguiente." },
  { titulo: "DÍA DE DESCANSO Y FESTIVOS", texto: "* Si se convoca al técnico en un día de descanso, con acuerdo de todas las partes, ese día se paga al valor de un día normal incrementado un 100% (el doble), con las horas extra y de recuperación también dobladas.\n* Un festivo nacional obligatorio dentro de la semana de trabajo se cobra como un día normal doblado.\n* Si se añade un sexto día a la semana de 5 días, el descanso entre semanas pasa a 36 horas." },
  { titulo: "COMIDA", texto: "* Si la pausa para comer es inferior a 1 hora, o no se produce durante el rodaje, se incluye en las horas de trabajo y puede contabilizarse como hora extra.\n* A partir de las 20:00, o tras un máximo de 7 horas desde el fin de la comida anterior, corresponde una segunda comida, con pausa no inferior a 30 minutos. Si la pausa no se produce, cuenta como hora extra y la comida se paga contra factura (mínimo 15 €).\n* Si el lugar o el catering no cumple los requisitos mínimos de higiene y calidad, la comida se paga contra factura (mínimo 15 €)." },
  { titulo: "HORARIO CONTINUO", texto: "* La pausa para comer debe hacerse antes de la 7ª hora consecutiva de trabajo en el set, contada desde la convocatoria. De lo contrario, el horario se considera continuo.\n* En ese caso las horas extra empiezan a contarse desde la 8ª hora, contando ya la hora de la comida como hora extra." },
  { titulo: "DESPLAZAMIENTOS", texto: "* Desde la plaza Marquês de Pombal (Lisboa), la casa de alquiler de material o el hotel si es ese el alojamiento, el tiempo de transporte en vehículos ligeros se calcula así:\n* Zona 0 – Lisboa ciudad — no se cobra tiempo de transporte, salvo que el técnico deba ir a la casa de alquiler, garaje, etc.\n* Zona 1 – hasta 25 km — 30 min por trayecto\n* Zona 2 – de 25 a 50 km — 45 min por trayecto\n* Zona 3 – de 50 a 100 km — 60 min (1 h) por trayecto\n* Zona 4 – más de 100 km o 1 h de transporte — derecho a alojamiento.\n* Sin alojamiento, la pausa para comer debe hacerse antes de la 7ª hora consecutiva contada desde donde empieza el transporte; si no, se considera horario continuo.\n* Excepción: el técnico que deba desplazarse a un lugar (casa de material, garaje u otro) para conducir un vehículo de material empieza allí su jornada." },
];

const FR: CondBox[] = [
  { titulo: "HEURE SUPPLÉMENTAIRE A", texto: "* Les heures supplémentaires A sont facturées une fois l'horaire de travail du département accompli (11 heures : 10 h de travail + 1 h de repas).\n* En horaire continu, elles sont facturées à partir de la 8e heure de travail." },
  { titulo: "HEURE SUPPLÉMENTAIRE B", texto: "* Les heures supplémentaires B sont facturées selon ce que stipule le département." },
  { titulo: "HEURE DE RÉCUPÉRATION", texto: "* Facturée lorsque l'intervalle entre deux jours de travail consécutifs est inférieur à 10 heures, selon ce que stipule le département.\n* Facturée lorsque l'intervalle entre le dernier jour de la semaine et le début de la suivante est inférieur à 60 heures (semaine de 5 jours) ou 36 heures (semaine de 6 jours). La demi-heure est arrondie à l'heure suivante." },
  { titulo: "JOUR DE REPOS ET FÉRIÉS", texto: "* Si le technicien est convoqué un jour de repos, avec l'accord de toutes les parties, ce jour est payé au tarif d'une journée normale majoré de 100 % (le double), les heures supplémentaires et de récupération étant également doublées.\n* Un jour férié obligatoire tombant dans la semaine de travail est facturé comme une journée normale doublée.\n* Si un sixième jour est ajouté à une semaine de 5 jours, le repos entre semaines passe à 36 heures." },
  { titulo: "REPAS", texto: "* Si la pause repas est inférieure à 1 heure, ou n'a pas lieu pendant le tournage, elle est comptée dans le temps de travail et peut être facturée en heure supplémentaire.\n* À partir de 20 h, ou au plus 7 heures après la fin du repas précédent, un second repas est dû, avec une pause d'au moins 30 minutes. Si la pause n'a pas lieu, elle compte en heure supplémentaire et le repas est payé sur facture (au moins 15 €).\n* Si le lieu ou le traiteur ne respecte pas les conditions minimales d'hygiène et de qualité, le repas est payé sur facture (au moins 15 €)." },
  { titulo: "HORAIRE CONTINU", texto: "* La pause repas doit avoir lieu avant la 7e heure consécutive de travail sur le plateau, comptée depuis la convocation. Sinon, l'horaire est considéré comme continu.\n* Dans ce cas, les heures supplémentaires commencent à la 8e heure, l'heure du repas comptant déjà comme heure supplémentaire." },
  { titulo: "DÉPLACEMENTS", texto: "* Depuis la place Marquês de Pombal (Lisbonne), le loueur de matériel ou l'hôtel s'il s'agit de l'hébergement, le temps de transport en véhicule léger est calculé ainsi :\n* Zone 0 – Lisbonne ville — pas de temps de transport facturé, sauf si le technicien doit passer chez le loueur, au garage, etc.\n* Zone 1 – jusqu'à 25 km — 30 min par trajet\n* Zone 2 – de 25 à 50 km — 45 min par trajet\n* Zone 3 – de 50 à 100 km — 60 min (1 h) par trajet\n* Zone 4 – plus de 100 km ou 1 h de transport — droit à l'hébergement.\n* Sans hébergement, la pause repas doit avoir lieu avant la 7e heure consécutive comptée depuis le départ du transport ; sinon, horaire continu.\n* Exception : le technicien qui doit se rendre sur un lieu (loueur, garage ou autre) pour conduire un véhicule de matériel commence sa journée à cet endroit." },
];

const DE: CondBox[] = [
  { titulo: "ÜBERSTUNDE A", texto: "* Überstunden A werden berechnet, sobald der Arbeitstag der Abteilung erfüllt ist (11 Stunden: 10 h Arbeit + 1 h Essenspause).\n* Bei durchgehender Arbeitszeit werden sie ab der 8. Arbeitsstunde berechnet." },
  { titulo: "ÜBERSTUNDE B", texto: "* Überstunden B werden nach Vorgabe der Abteilung berechnet." },
  { titulo: "ERHOLUNGSSTUNDE", texto: "* Wird berechnet, wenn die Ruhezeit zwischen zwei aufeinanderfolgenden Arbeitstagen unter 10 Stunden liegt, nach Vorgabe der Abteilung.\n* Wird berechnet, wenn die Ruhezeit zwischen dem letzten Tag der Woche und dem Beginn der nächsten unter 60 Stunden (5-Tage-Woche) bzw. 36 Stunden (6-Tage-Woche) liegt. Eine halbe Stunde wird auf die nächste Stunde aufgerundet." },
  { titulo: "FREIER TAG UND FEIERTAGE", texto: "* Wird die Fachkraft an einem freien Tag eingesetzt, nach Vereinbarung aller Beteiligten, gilt dieser Tag als normaler Tag mit 100 % Zuschlag (doppelt), Überstunden und Erholungsstunden ebenfalls verdoppelt.\n* Ein gesetzlicher Feiertag innerhalb der Arbeitswoche wird als normaler Tag doppelt berechnet.\n* Wird einer 5-Tage-Woche ein sechster Tag hinzugefügt, beträgt die Ruhezeit zwischen den Wochen 36 Stunden." },
  { titulo: "VERPFLEGUNG", texto: "* Ist die Essenspause kürzer als 1 Stunde oder findet sie während des Drehs nicht statt, zählt sie zur Arbeitszeit und kann als Überstunde berechnet werden.\n* Ab 20 Uhr oder spätestens 7 Stunden nach Ende der vorherigen Mahlzeit ist eine zweite Mahlzeit fällig, mit mindestens 30 Minuten Pause. Findet die Pause nicht statt, zählt sie als Überstunde und die Mahlzeit wird gegen Rechnung bezahlt (mindestens 15 €).\n* Erfüllen Ort oder Catering die Mindestanforderungen an Hygiene und Qualität nicht, wird die Mahlzeit gegen Rechnung bezahlt (mindestens 15 €)." },
  { titulo: "DURCHGEHENDE ARBEITSZEIT", texto: "* Die Essenspause muss bis zur 7. aufeinanderfolgenden Arbeitsstunde am Set stattfinden, gezählt ab Crew Call. Andernfalls gilt der Tag als durchgehende Arbeitszeit.\n* In diesem Fall beginnen die Überstunden ab der 8. Stunde, wobei die Essensstunde bereits als Überstunde zählt." },
  { titulo: "FAHRTEN", texto: "* Ab dem Marquês-de-Pombal-Platz (Lissabon), dem Equipmentverleih oder dem Hotel (falls dort untergebracht) wird die Fahrzeit für Pkw wie folgt berechnet:\n* Zone 0 – Stadt Lissabon — keine Fahrzeit, sofern die Fachkraft nicht zum Verleih, zur Garage usw. muss.\n* Zone 1 – bis 25 km — 30 Min. pro Strecke\n* Zone 2 – 25 bis 50 km — 45 Min. pro Strecke\n* Zone 3 – 50 bis 100 km — 60 Min. (1 h) pro Strecke\n* Zone 4 – über 100 km oder 1 h Fahrt — Anspruch auf Unterkunft.\n* Ohne Unterkunft muss die Essenspause bis zur 7. aufeinanderfolgenden Stunde ab Fahrtbeginn stattfinden; sonst gilt durchgehende Arbeitszeit.\n* Ausnahme: Wer zu einem Ort (Verleih, Garage o. Ä.) muss, um ein Equipmentfahrzeug zu fahren, beginnt den Arbeitstag dort." },
];

const IT: CondBox[] = [
  { titulo: "ORA EXTRA A", texto: "* Le ore extra A si addebitano una volta completato l'orario di lavoro del reparto (11 ore: 10 h di lavoro + 1 h di pasto).\n* In orario continuato si addebitano dall'8ª ora di lavoro." },
  { titulo: "ORA EXTRA B", texto: "* Le ore extra B si addebitano secondo quanto stabilito dal reparto." },
  { titulo: "ORA DI RECUPERO", texto: "* Addebitata quando l'intervallo tra due giorni di lavoro consecutivi è inferiore a 10 ore, secondo quanto stabilito dal reparto.\n* Addebitata quando l'intervallo tra l'ultimo giorno della settimana e l'inizio della successiva è inferiore a 60 ore (settimana di 5 giorni) o 36 ore (settimana di 6 giorni). La mezz'ora si arrotonda all'ora successiva." },
  { titulo: "GIORNO DI RIPOSO E FESTIVI", texto: "* Se il tecnico è convocato in un giorno di riposo, con l'accordo di tutte le parti, quel giorno è pagato al valore di una giornata normale maggiorata del 100% (il doppio), con ore extra e di recupero anch'esse raddoppiate.\n* Un festivo nazionale obbligatorio all'interno della settimana lavorativa si addebita come giornata normale raddoppiata.\n* Se si aggiunge un sesto giorno a una settimana di 5, il riposo tra settimane passa a 36 ore." },
  { titulo: "PASTO", texto: "* Se la pausa pasto è inferiore a 1 ora, o non avviene durante le riprese, è inclusa nelle ore di lavoro e può essere conteggiata come ora extra.\n* Dalle 20:00, o al massimo 7 ore dopo la fine del pasto precedente, è dovuto un secondo pasto, con pausa non inferiore a 30 minuti. Se la pausa non avviene, conta come ora extra e il pasto è pagato su fattura (minimo 15 €).\n* Se il luogo o il catering non rispetta i requisiti minimi di igiene e qualità, il pasto è pagato su fattura (minimo 15 €)." },
  { titulo: "ORARIO CONTINUATO", texto: "* La pausa pasto deve avvenire entro la 7ª ora consecutiva di lavoro sul set, contata dalla convocazione. In caso contrario l'orario si considera continuato.\n* In tal caso le ore extra si contano dall'8ª ora, con l'ora del pasto già conteggiata come ora extra." },
  { titulo: "TRASFERTE", texto: "* Da piazza Marquês de Pombal (Lisbona), dal noleggio attrezzature o dall'hotel se è quello l'alloggio, il tempo di trasporto per veicoli leggeri si calcola così:\n* Zona 0 – città di Lisbona — nessun tempo di trasporto, salvo che il tecnico debba passare dal noleggio, garage, ecc.\n* Zona 1 – fino a 25 km — 30 min per tratta\n* Zona 2 – da 25 a 50 km — 45 min per tratta\n* Zona 3 – da 50 a 100 km — 60 min (1 h) per tratta\n* Zona 4 – oltre 100 km o 1 h di trasporto — diritto all'alloggio.\n* Senza alloggio, la pausa pasto deve avvenire entro la 7ª ora consecutiva contata dal luogo di partenza del trasporto; altrimenti orario continuato.\n* Eccezione: il tecnico che deve recarsi in un luogo (noleggio, garage o altro) per guidare un veicolo attrezzature inizia lì la giornata." },
];

const NL: CondBox[] = [
  { titulo: "OVERUUR A", texto: "* Overuren A worden berekend zodra de werkdag van de afdeling is volgemaakt (11 uur: 10 u werk + 1 u maaltijd).\n* Bij een doorlopend rooster worden ze berekend vanaf het 8e werkuur." },
  { titulo: "OVERUUR B", texto: "* Overuren B worden berekend zoals de afdeling bepaalt." },
  { titulo: "HERSTELUUR", texto: "* Berekend wanneer de rust tussen twee opeenvolgende werkdagen korter is dan 10 uur, zoals de afdeling bepaalt.\n* Berekend wanneer de rust tussen de laatste dag van de week en het begin van de volgende korter is dan 60 uur (5-daagse week) of 36 uur (6-daagse week). Een half uur wordt afgerond naar het volgende uur." },
  { titulo: "VRIJE DAG EN FEESTDAGEN", texto: "* Wordt de crewlid opgeroepen op een vrije dag, met instemming van alle partijen, dan geldt die dag als een normale dag met 100% toeslag (dubbel), overuren en hersteluren eveneens verdubbeld.\n* Een wettelijke feestdag binnen de werkweek wordt als een normale dag dubbel berekend.\n* Wordt aan een 5-daagse week een zesde dag toegevoegd, dan wordt de rust tussen weken 36 uur." },
  { titulo: "MAALTIJD", texto: "* Is de maaltijdpauze korter dan 1 uur, of vindt hij niet plaats tijdens de opnames, dan telt hij als werktijd en kan hij als overuur worden berekend.\n* Vanaf 20:00, of uiterlijk 7 uur na het einde van de vorige maaltijd, is een tweede maaltijd verschuldigd, met een pauze van minstens 30 minuten. Vindt de pauze niet plaats, dan telt hij als overuur en wordt de maaltijd op factuur betaald (minstens € 15).\n* Voldoet de locatie of catering niet aan de minimale eisen van hygiëne en kwaliteit, dan wordt de maaltijd op factuur betaald (minstens € 15)." },
  { titulo: "DOORLOPEND ROOSTER", texto: "* De maaltijdpauze moet uiterlijk in het 7e opeenvolgende werkuur op de set plaatsvinden, geteld vanaf de crew call. Anders geldt de dag als doorlopend rooster.\n* In dat geval beginnen de overuren vanaf het 8e uur, waarbij het maaltijduur zelf al als overuur telt." },
  { titulo: "REISTIJD", texto: "* Vanaf het Marquês de Pombal-plein (Lissabon), de apparatuurverhuur of het hotel als dat de accommodatie is, wordt de reistijd voor lichte voertuigen als volgt berekend:\n* Zone 0 – stad Lissabon — geen reistijd, tenzij het crewlid naar de verhuur, garage enz. moet.\n* Zone 1 – tot 25 km — 30 min per rit\n* Zone 2 – 25 tot 50 km — 45 min per rit\n* Zone 3 – 50 tot 100 km — 60 min (1 u) per rit\n* Zone 4 – meer dan 100 km of 1 u reistijd — recht op accommodatie.\n* Zonder accommodatie moet de maaltijdpauze uiterlijk in het 7e opeenvolgende uur vanaf het vertrekpunt plaatsvinden; anders geldt doorlopend rooster.\n* Uitzondering: wie naar een locatie (verhuur, garage of anders) moet om een apparatuurwagen te rijden, begint daar de werkdag." },
];

const PL: CondBox[] = [
  { titulo: "NADGODZINA A", texto: "* Nadgodziny A nalicza się po wypełnieniu dnia pracy obowiązującego w dziale (11 godzin: 10 h pracy + 1 h posiłku).\n* Przy pracy ciągłej nalicza się je od 8. godziny pracy." },
  { titulo: "NADGODZINA B", texto: "* Nadgodziny B nalicza się zgodnie z ustaleniami działu." },
  { titulo: "GODZINA ODPOCZYNKU WYRÓWNAWCZEGO", texto: "* Naliczana, gdy przerwa między dwoma kolejnymi dniami pracy jest krótsza niż 10 godzin, zgodnie z ustaleniami działu.\n* Naliczana, gdy przerwa między ostatnim dniem tygodnia a początkiem następnego jest krótsza niż 60 godzin (tydzień 5-dniowy) lub 36 godzin (tydzień 6-dniowy). Pół godziny zaokrągla się w górę do pełnej godziny." },
  { titulo: "DZIEŃ WOLNY I ŚWIĘTA", texto: "* Jeśli technik zostanie wezwany w dniu wolnym, za zgodą wszystkich stron, dzień ten jest płatny jak dzień normalny powiększony o 100% (podwójnie), a nadgodziny i godziny wyrównawcze również podwójnie.\n* Ustawowe święto przypadające w tygodniu pracy rozlicza się jak dzień normalny podwójnie.\n* Jeśli do tygodnia 5-dniowego dodany zostanie szósty dzień, odpoczynek między tygodniami wynosi 36 godzin." },
  { titulo: "POSIŁEK", texto: "* Jeśli przerwa na posiłek jest krótsza niż 1 godzina lub nie ma jej podczas zdjęć, wlicza się ją do czasu pracy i może być rozliczona jako nadgodzina.\n* Od 20:00 lub najpóźniej 7 godzin po zakończeniu poprzedniego posiłku należy się drugi posiłek, z przerwą nie krótszą niż 30 minut. Jeśli przerwy nie ma, liczy się jako nadgodzina, a posiłek jest płatny na fakturę (nie mniej niż 15 €).\n* Jeśli miejsce lub catering nie spełnia minimalnych wymogów higieny i jakości, posiłek jest płatny na fakturę (nie mniej niż 15 €)." },
  { titulo: "PRACA CIĄGŁA", texto: "* Przerwa na posiłek musi nastąpić do 7. kolejnej godziny pracy na planie, licząc od wezwania ekipy. W przeciwnym razie dzień traktuje się jako pracę ciągłą.\n* Wówczas nadgodziny liczy się od 8. godziny, a godzina posiłku już liczy się jako nadgodzina." },
  { titulo: "DOJAZDY", texto: "* Od placu Marquês de Pombal (Lizbona), wypożyczalni sprzętu lub hotelu, jeśli tam jest zakwaterowanie, czas dojazdu pojazdem osobowym liczy się następująco:\n* Strefa 0 – miasto Lizbona — bez czasu dojazdu, chyba że technik musi jechać do wypożyczalni, garażu itp.\n* Strefa 1 – do 25 km — 30 min za przejazd\n* Strefa 2 – 25 do 50 km — 45 min za przejazd\n* Strefa 3 – 50 do 100 km — 60 min (1 h) za przejazd\n* Strefa 4 – ponad 100 km lub 1 h dojazdu — prawo do zakwaterowania.\n* Bez zakwaterowania przerwa na posiłek musi nastąpić do 7. kolejnej godziny liczonej od miejsca rozpoczęcia dojazdu; inaczej praca ciągła.\n* Wyjątek: technik, który musi udać się w miejsce (wypożyczalnia, garaż lub inne), by prowadzić pojazd ze sprzętem, rozpoczyna tam dzień pracy." },
];

export function condBoxesCinemaFor(locale: string): CondBox[] {
  const l = (locale || "pt").toLowerCase();
  if (l.startsWith("pt")) return PT;
  if (l.startsWith("es")) return ES;
  if (l.startsWith("fr")) return FR;
  if (l.startsWith("de")) return DE;
  if (l.startsWith("it")) return IT;
  if (l.startsWith("nl")) return NL;
  if (l.startsWith("pl")) return PL;
  return EN;
}
